### ISSUE TITLE
Что означает название motto, motto1 и  motto2?

### ISSUE THREAD

**Issue by frontgirl** [Sonrisa86/diplomaNetology#1]
https://github.com/Sonrisa86/diplomaNetology/blob/97f62d2fa5b1dedda2af0e16f695488344fe9a9c/index.html#L22

Названия классов должны быть понятны

**Comment by Sonrisa86** [comment]
motto в переводе с английского - "девиз, лозунг".

**Comment by frontgirl** [comment]
Ок, принимается (я знала только значение "идея", поэтому меня немного смутило). Тогда нужно только избавиться от цифр в названиях классов, но это можно сделать в последнюю очередь.
